// Profile objects extracted from the main app
export const profiles = {
  me: {
    id: 'me',
    username: 'me',
    name: 'Alex Kumar',
    title: 'CS Student @ NTU',
    role: 'Student',
    audience: 'Student',
    domain: 'DeepTech',
    intent: 'Co-founder',
    commitment: 'Flexible',
    workStyle: 'Hybrid',
    location: 'Singapore',
    avatar: 'AK',
    tone: 'violet',
    match: 73,
    verified: false,
    bio: 'Building ML and front-end prototypes with a focus on practical learning, mentorship, and portfolio growth.',
    headline: 'Building ML and front-end projects in public.',
    skills: ['React', 'Python', 'SQL', 'ML'],
    goals: ['Find mentor', 'Book 1:1 sessions', 'Build portfolio projects'],
    why: ['Complete your social links', 'Book your first session', 'Attend an event'],
    mutuals: 5,
    responseRate: '94%',
    avgResponse: '2 hours',
    views: 124,
    sessions: 4,
    events: 3,
    companyStage: '',
    links: ['LinkedIn', 'GitHub', 'Portfolio'],
    cover: 'linear-gradient(135deg, rgba(14, 207, 191, 0.24), rgba(108, 92, 231, 0.18)), linear-gradient(180deg, rgba(17, 17, 17, 0.98), rgba(8, 8, 8, 0.92))',
  },
  sarah: {
    id: 'sarah-chen',
    username: 'sarah-chen',
    name: 'Sarah Chen',
    title: 'Product Manager @ Grab',
    role: 'Professional',
    audience: 'Professional',
    domain: 'Product',
    intent: 'Advisor',
    commitment: 'Flexible',
    workStyle: 'Hybrid',
    location: 'Singapore',
    avatar: 'SC',
    tone: 'teal',
    match: 94,
    verified: true,
    bio: 'Product leader with 7 years in consumer apps, open to mentoring students in PM and UX.',
    headline: 'Open to mentoring students in PM and UX.',
    skills: ['UX', 'Product', 'Agile', 'Roadmapping'],
    goals: ['Mentoring', 'Project reviews', 'Speaking opportunities'],
    why: ['Shared product signals', 'Fast response history', 'Evening availability'],
    mutuals: 6,
    responseRate: '94%',
    avgResponse: '2 hours',
    views: 188,
    sessions: 19,
    events: 6,
    companyStage: 'Series A',
    links: ['LinkedIn', 'Portfolio'],
    cover: 'linear-gradient(135deg, rgba(14, 207, 191, 0.22), rgba(14, 207, 191, 0.06)), linear-gradient(180deg, rgba(17, 17, 17, 0.98), rgba(8, 8, 8, 0.92))',
  },
  nora: {
    id: 'nora-khan',
    username: 'nora-khan',
    name: 'Nora Khan',
    title: 'UX Designer',
    role: 'Professional',
    audience: 'Professional',
    domain: 'Design',
    intent: 'Side project',
    commitment: 'Part-time',
    workStyle: 'Remote',
    location: 'Remote',
    avatar: 'NK',
    tone: 'rose',
    match: 96,
    verified: true,
    bio: 'Design lead who likes product reviews, portfolio feedback, and tasteful side projects.',
    headline: 'Open to collaborating on a portfolio project.',
    skills: ['Figma', 'React', 'Research', 'Brand'],
    goals: ['Portfolio swaps', 'Co-building', 'Mentoring'],
    why: ['Strong design overlap', 'High intent alignment', 'Similar pace'],
    mutuals: 3,
    responseRate: '91%',
    avgResponse: '3 hours',
    views: 112,
    sessions: 11,
    events: 4,
    companyStage: '',
    links: ['LinkedIn', 'Portfolio'],
    cover: 'linear-gradient(135deg, rgba(252, 114, 177, 0.22), rgba(108, 92, 231, 0.08)), linear-gradient(180deg, rgba(17, 17, 17, 0.98), rgba(8, 8, 8, 0.92))',
  },
  raj: {
    id: 'raj-patel',
    username: 'raj-patel',
    name: 'Raj Patel',
    title: 'Full-stack Engineer @ Stripe',
    role: 'Professional',
    audience: 'Professional',
    domain: 'Engineering',
    intent: 'Tech collab',
    commitment: 'Flexible',
    workStyle: 'Remote',
    location: 'Remote',
    avatar: 'RP',
    tone: 'violet',
    match: 91,
    verified: true,
    bio: 'Engineer who likes mentorship, project reviews, and helping people ship clean software faster.',
    headline: 'Looking for a design-savvy side-project collaborator.',
    skills: ['React', 'Node', 'System Design', 'Testing'],
    goals: ['Collaboration', 'Internship pipeline', 'Office hours'],
    why: ['Shared stack signals', 'Project momentum', 'Remote-friendly'],
    mutuals: 4,
    responseRate: '97%',
    avgResponse: '1 hour',
    views: 141,
    sessions: 14,
    events: 5,
    companyStage: '',
    links: ['LinkedIn', 'GitHub'],
    cover: 'linear-gradient(135deg, rgba(108, 92, 231, 0.22), rgba(14, 207, 191, 0.08)), linear-gradient(180deg, rgba(17, 17, 17, 0.98), rgba(8, 8, 8, 0.92))',
  },
  priya: {
    id: 'priya-khan',
    username: 'priya-khan',
    name: 'Priya Khan',
    title: 'ML Engineer @ FinPulse',
    role: 'Professional',
    audience: 'Professional',
    domain: 'FinTech',
    intent: 'Co-founder',
    commitment: 'Full-time',
    workStyle: 'Hybrid',
    location: 'Chennai',
    avatar: 'PK',
    tone: 'amber',
    match: 95,
    verified: true,
    bio: 'ML engineer who wants to build a fintech infrastructure product with a serious partner.',
    headline: 'Building credit scoring infrastructure and open to co-founding.',
    skills: ['Python', 'ML', 'Data', 'Finance'],
    goals: ['Co-founder', 'Technical partner', 'Advisor'],
    why: ['Same domain', 'High signal profile', 'Flexible availability'],
    mutuals: 8,
    responseRate: '90%',
    avgResponse: '2 hours',
    views: 203,
    sessions: 9,
    events: 7,
    companyStage: 'Seed',
    links: ['LinkedIn', 'Portfolio'],
    cover: 'linear-gradient(135deg, rgba(245, 158, 11, 0.2), rgba(14, 207, 191, 0.08)), linear-gradient(180deg, rgba(17, 17, 17, 0.98), rgba(8, 8, 8, 0.92))',
  },
  liam: {
    id: 'liam-owen',
    username: 'liam-owen',
    name: 'Liam Owen',
    title: 'Data Scientist',
    role: 'Professional',
    audience: 'Professional',
    domain: 'DeepTech',
    intent: 'Advisor',
    commitment: 'Part-time',
    workStyle: 'Remote',
    location: 'London',
    avatar: 'LO',
    tone: 'teal',
    match: 89,
    verified: false,
    bio: 'Data scientist who mentors on interviews, ML projects, and building good habits.',
    headline: 'Available for mentoring and 1:1 reviews.',
    skills: ['Python', 'ML', 'Analytics', 'Research'],
    goals: ['Mentoring', 'Project reviews', 'Community talks'],
    why: ['Clear mentorship intent', 'Complementary skills', 'Remote-friendly'],
    mutuals: 2,
    responseRate: '92%',
    avgResponse: '4 hours',
    views: 98,
    sessions: 8,
    events: 3,
    companyStage: '',
    links: ['LinkedIn'],
    cover: 'linear-gradient(135deg, rgba(14, 207, 191, 0.18), rgba(108, 92, 231, 0.08)), linear-gradient(180deg, rgba(17, 17, 17, 0.98), rgba(8, 8, 8, 0.92))',
  },
  mei: {
    id: 'mei-lin',
    username: 'mei-lin',
    name: 'Mei Lin',
    title: 'Computer Science Student',
    role: 'Student',
    audience: 'Student',
    domain: 'Engineering',
    intent: 'Tech collab',
    commitment: 'Flexible',
    workStyle: 'Hybrid',
    location: 'Kuala Lumpur',
    avatar: 'ML',
    tone: 'rose',
    match: 88,
    verified: false,
    bio: 'Bootcamp grad and CS student building ML and front-end projects while applying for internships.',
    headline: 'Seeking internship guidance and product feedback.',
    skills: ['Python', 'React', 'SQL', 'ML'],
    goals: ['Find mentor', 'Book 1:1 sessions', 'Build portfolio projects'],
    why: ['Goal alignment', 'Complementary skills', 'High engagement'],
    mutuals: 1,
    responseRate: '89%',
    avgResponse: '3 hours',
    views: 67,
    sessions: 3,
    events: 2,
    companyStage: '',
    links: ['LinkedIn', 'GitHub'],
    cover: 'linear-gradient(135deg, rgba(252, 114, 177, 0.18), rgba(14, 207, 191, 0.06)), linear-gradient(180deg, rgba(17, 17, 17, 0.98), rgba(8, 8, 8, 0.92))',
  },
  david: {
    id: 'david-brooks',
    username: 'david-brooks',
    name: 'David Brooks',
    title: 'Marketing Lead @ Notion',
    role: 'Professional',
    audience: 'Professional',
    domain: 'Marketing',
    intent: 'Advisor',
    commitment: 'Flexible',
    workStyle: 'Hybrid',
    location: 'London',
    avatar: 'DB',
    tone: 'amber',
    match: 87,
    verified: true,
    bio: 'Growth marketer open to speaking, reviewing pitches, and helping people sharpen positioning.',
    headline: 'Happy to host talks on growth and storytelling.',
    skills: ['Growth', 'Content', 'Brand', 'Community'],
    goals: ['Mentoring', 'Speaking', 'Advising'],
    why: ['Speaking interest', 'Strong network', 'Growth domain'],
    mutuals: 4,
    responseRate: '95%',
    avgResponse: '2 hours',
    views: 140,
    sessions: 7,
    events: 5,
    companyStage: '',
    links: ['LinkedIn'],
    cover: 'linear-gradient(135deg, rgba(245, 158, 11, 0.18), rgba(14, 207, 191, 0.06)), linear-gradient(180deg, rgba(17, 17, 17, 0.98), rgba(8, 8, 8, 0.92))',
  },
  ethan: {
    id: 'ethan-cho',
    username: 'ethan-cho',
    name: 'Ethan Cho',
    title: 'Founder @ ArcVector',
    role: 'Professional',
    audience: 'Professional',
    domain: 'SaaS',
    intent: 'Co-founder',
    commitment: 'Full-time',
    workStyle: 'Hybrid',
    location: 'Bangalore',
    avatar: 'EC',
    tone: 'violet',
    match: 92,
    verified: true,
    bio: 'Founder building a workflow automation product and looking for technical and design depth.',
    headline: 'Looking for a technical co-founder or specialist collaborators.',
    skills: ['Product', 'Operations', 'SaaS', 'Strategy'],
    goals: ['Co-founder', 'Hiring', 'Advising'],
    why: ['Founder intent', 'Stage overlap', 'High activity'],
    mutuals: 5,
    responseRate: '93%',
    avgResponse: '1 hour',
    views: 176,
    sessions: 12,
    events: 8,
    companyStage: 'Seed',
    links: ['LinkedIn', 'Website'],
    cover: 'linear-gradient(135deg, rgba(108, 92, 231, 0.2), rgba(245, 158, 11, 0.06)), linear-gradient(180deg, rgba(17, 17, 17, 0.98), rgba(8, 8, 8, 0.92))',
  },
};

// Derived collections
export const studentDiscoverProfiles = [profiles.sarah, profiles.raj, profiles.priya, profiles.liam, profiles.david, profiles.nora, profiles.mei];
export const proDiscoverProfiles = [profiles.mei, profiles.nora, profiles.raj, profiles.priya, profiles.ethan, profiles.sarah, profiles.liam];

export const studentConnections = {
  suggested: [profiles.nora, profiles.priya, profiles.raj],
  pendingReceived: [profiles.mei, profiles.liam],
  pendingSent: [profiles.sarah],
  connected: [profiles.sarah, profiles.raj],
  shortlisted: [profiles.priya, profiles.nora],
};

export const studentThreads = [
  {
    id: 'sarah-chen',
    person: profiles.sarah,
    status: 'Online',
    unread: 2,
    last: 'Want to hop on a quick call next week?',
    time: '2m',
    messages: [
      { id: 1, from: 'them', body: 'Hey Alex, your portfolio looks strong.', time: '10:22' },
      { id: 2, from: 'me', body: 'Thanks. I would love feedback on PM skills.', time: '10:24' },
      { id: 3, from: 'them', body: 'Want to hop on a quick call next week?', time: '10:25' },
    ],
  },
  {
    id: 'raj-patel',
    person: profiles.raj,
    status: 'Typing',
    unread: 0,
    last: 'I can send a starter repo if you want.',
    time: '1h',
    messages: [
      { id: 1, from: 'them', body: 'Loved the ML project you shared.', time: '09:04' },
      { id: 2, from: 'me', body: 'Thanks, I am trying to turn it into a portfolio piece.', time: '09:07' },
      { id: 3, from: 'them', body: 'I can send a starter repo if you want.', time: '09:08' },
    ],
  },
  {
    id: 'mei-lin',
    person: profiles.mei,
    status: 'Offline',
    unread: 1,
    last: 'Can you review my resume this week?',
    time: 'Yesterday',
    messages: [
      { id: 1, from: 'them', body: 'Can you review my resume this week?', time: 'Yesterday' },
      { id: 2, from: 'me', body: 'Yes. Send the latest version and the target role.', time: 'Yesterday' },
    ],
  },
];

export const proThreads = [
  {
    id: 'ethan-cho',
    person: profiles.ethan,
    status: 'Online',
    unread: 1,
    last: 'Could we talk about a co-founder profile?',
    time: '8m',
    messages: [
      { id: 1, from: 'me', body: 'Your product direction feels strong.', time: '10:10' },
      { id: 2, from: 'them', body: 'Could we talk about a co-founder profile?', time: '10:11' },
      { id: 3, from: 'me', body: 'Yes, I can share a few options and next steps.', time: '10:14' },
    ],
  },
  {
    id: 'sarah-chen',
    person: profiles.sarah,
    status: 'Last seen 2h ago',
    unread: 0,
    last: 'The workshop deck is ready for review.',
    time: '2h',
    messages: [
      { id: 1, from: 'them', body: 'The workshop deck is ready for review.', time: '08:40' },
      { id: 2, from: 'me', body: 'Great, I will review it before lunch.', time: '08:43' },
    ],
  },
  {
    id: 'priya-khan',
    person: profiles.priya,
    status: 'Online',
    unread: 2,
    last: 'The next session should include architecture notes.',
    time: '30m',
    messages: [
      { id: 1, from: 'them', body: 'The next session should include architecture notes.', time: '11:00' },
      { id: 2, from: 'me', body: 'Agreed. I will add them to the brief.', time: '11:04' },
    ],
  },
];
