export const SOCKET_EVENTS = Object.freeze({
  JOIN_ROOM: 'join_room',
  LEAVE_ROOM: 'leave_room',
  SEND_MESSAGE: 'send_message',
  RECEIVE_MESSAGE: 'receive_message',
  TYPING_START: 'typing_start',
  TYPING_STOP: 'typing_stop',
  USER_TYPING: 'user_typing',
  TYPING_STOPPED: 'typing_stopped',
  MESSAGE_READ: 'message_read',
  MESSAGE_READ_ACK: 'message_read_ack',
  NOTIFICATION: 'notification',
  PRESENCE_UPDATE: 'presence_update',
  CALL_JOIN: 'call_join',
  CALL_LEAVE: 'call_leave',
  CALL_READY: 'call_ready',
  CALL_OFFER: 'call_offer',
  CALL_ANSWER: 'call_answer',
  CALL_ICE_CANDIDATE: 'call_ice_candidate',
  CALL_ENDED: 'call_ended',
});
